name: helloworld
on:
  push:
    branches: [main]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: actions/hello-world-docker-action@v2
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
      - run: | 
          docker build . -f Dockerfile -t billybackmanh/helloworld:latest \
             --build-arg ARTIFACTORY_USERNAME=${{ secrets.SE_KAROLINSKA_ARTIFACTORY_CI_USERNAME }}
      - run: docker push billybackmanh/helloworld:latest