name: helloworld
on:
  push:
    branches: [main]

jobs:
  docker-job:
    runs-on:
      - docker
      - self-hosted
     steps:
      - name: Checkout main
        uses: actions/checkout@v3
      -run: | 
        docker build . -f Dockerfile -t billybackmanh/helloworld:latest \
          --build-arg ARTIFACTORY_USERNAME=${{ secrets.SE_KAROLINSKA_ARTIFACTORY_CI_USERNAME }}
      - run: docker push billybackmanh/helloworld:latest